name: "DHCPd Server"
version: "0.5"
slug: adv-dhcp-server
description: >-
  Advanced DHCP Server
arch:
  - amd64
  - armhf
  - armv7
  - aarch64
  - i386
url: "https://github.com/spidererrol/hass-adv-dhcp-server"
ports:
  67/tcp: 67
host_network: true
startup: "before"
init: false
options:
  device: eth0
schema:
  device: str
map:
  - "addon_config:rw"
